---
- hosts: all
  tasks:
    - name: OS/Distro Specific Setup
      include: Setup.yml

    - name: disable sysklogd (if present)
      service: name=syslog enabled=no
      ignore_errors: true
    - name: enable rsyslog (if not)
      when: ansible_os_family != "FreeBSD" and ansible_service_mgr != "systemd"
      service: name=rsyslog enabled=yes
      ignore_errors: true
    - name: enable rsyslog (if not)
      when: ansible_os_family == "FreeBSD"
      service: name=rsyslogd enabled=yes
      ignore_errors: true

    - name: remove cloud user
      user: name=cloud state=absent
    

    - name: add CloudStack login splash (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      template: src=templates/Generic/motd.j2 dest=/etc/motd.tail
    - name: add CloudStack login spash (Others)
      when: ansible_distribution != "Ubuntu"
      template: src=templates/Generic/motd.j2 dest=/etc/motd
      
    - name: create ssh directory
      file: state=directory mode=0700 path=/root/.ssh

    - name: create directory to store cloudstack client scripts
      file: state=directory mode=0755 path=/usr/share/cloudstack

    - name: setup common functions for init scripts
      include: Template-Cloud-Functions.yml

    - name: setup init services
      include: Template-Create-Services.yml
    - name: register init services
      include: Template-Enable-Services.yml

    - name: setup networking
      include: Setup-Networking.yml
    - name: instance cleanup
      include: Template-Cleanup.yml

    - name: set root password to "cloudstack" (in case init scripts fail)
      when: ansible_os_family != "Mageia"
      user: name=root update_password=always password=$6$wbv2I8c6qYN9$5P8feP936YgJelVZFts0grMjYevgQZ6gvu8gC06dxwWk0t02qPhM7X9xEZn6CU2AXMDZC9RW8Gnz7eE5WfH4B/

    - name: anonymize vm
      include: Template-Anonymize.yml