#!/bin/bash -x
sleep 5
#
# Init file for User-Data download and execution
#
# chkconfig: 345 99 02
# description: User-Data Download Client
# Modify this line to specify the user (default is root)
user=root

# Add your DHCP lease folders here
if [ -f /etc/debian_version ]; then
  # Ubuntu
  DHCP_FOLDERS="/var/lib/dhcpcd/dhcpcd-eth0.*"
elif [ -f /etc/redhat-release ]; then
  # Redhat / CentOS / Scientific Linux
  #DHCP_FOLDERS="/var/lib/dhclient/* /var/lib/dhcp3/*"
  DHCP_FOLDERS="/var/lib/dhclient/* /var/lib/dhcp3/* /var/lib/dhcp/* /var/lib/NetworkManager/*"
else
  # Others
  DHCP_FOLDERS="/var/lib/dhclient/* /var/lib/dhcp3/*"
fi

# RHEL/CENTOS 7 use NetworkManager
# Don't know how to verify NetworkManager is being used via output of "systemctl status NetworkManager"
# So for now simply assuming it is being used.
DIST=$(lsb_release -i | sed 's/\t//g' |awk -F':' '{print $2}')
RELEASE=$(lsb_release -r | sed 's/\t//g' |awk -F':' '{print $2}')
if [[ "$DIST" == RedHat*||CentOS* ]]  &&  [[ "$RELEASE" == 7.* ]]; then
	HOSTNAME=$(tac /var/lib/NetworkManager/dhclient*eth0.lease | grep -m1 host-name | awk '{print $NF}' | tr -d '\;' | tr -d '"' | tail -1)
else
	HOSTNAME=$(tac /var/lib/dhc*/dhclient?eth0.leases | grep -m1 host-name | awk '{print $NF}' | tr -d '\;' | tr -d '"' | tail -1)
fi

CLOUD_DIR=/var/lib/cloud/instances/$HOSTNAME
USER_DATA=/var/lib/cloud/instances/$HOSTNAME/user-data
LOCK=/var/lib/cloud/user-data.ran
user_data_received=0
file_count=0

if [ -f "${LOCK}" ]
then
  logger -t "cloud" "User-Data appears to be executed once, skipping"
  exit 0
fi

if [ ! -d "${CLOUD_DIR}" ]
then
  mkdir -p "${CLOUD_DIR}"
fi

for DHCP_FILE in ${DHCP_FOLDERS}
do
  if [ -f "${DHCP_FILE}" ]
  then
    file_count=$((file_count+1))
  if [ -f /etc/debian_version ]; then
    # Ubuntu
    #USER_DATA_SERVER_IP=$(grep DHCPSID $DHCP_FILE | tail -1 |  egrep -o '([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})' )
    USER_DATA_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
  elif [ -f /etc/redhat-release ]; then
    # Redhat / CentOS / Scientific Linux
    USER_DATA_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
  else
    # Others
    USER_DATA_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
  fi

  if [ -n "${USER_DATA_SERVER_IP}" ]
  then
    logger -t "cloud" "Sending request to USER-DATA server at ${USER_DATA_SERVER_IP}"
    wget -t 3 -T 20 -O "${USER_DATA}" http://"${USER_DATA_SERVER_IP}"/latest/user-data 2>/dev/null
    if [ $? -eq 0 ]
    then
      logger -t "cloud" "Got user-data from server at ${USER_DATA_SERVER_IP}"
      if [ -s "${USER_DATA}" ]; then
        chmod 600 "${USER_DATA}"
        user_data_received=1
      else
        logger -t "cloud" "User-data is empty"
      fi
      break
    fi
    else
      logger -t "cloud" "Could not find user-data server IP in ${DHCP_FILE}"
    fi
  fi
done
# did we get the user-data?
if [ "${user_data_received}" == "0" ]
then
  logger -t "cloud" "Failed to get user-data from any server"
  exit 1
fi

# test/execute user-data
if [ "${user_data_received}" == "1" ]
then
  line1=$(head -1 "${USER_DATA}")
  echo "${line1}" | grep -q ^#!
  if [ $? -eq 0 ]; then
    if [ -f "${LOCK}" ]
    then
      logger -t "cloud" "User-Data appears to be executed once, skipping"
      exit 0
    else
      grep -r $'\r' "${USER_DATA}"
      if [ $? -ne 0 ]; then
        chmod 700 "${USER_DATA}"
        "${USER_DATA}"
      else
        sed -i -e 's/\r//g' "${USER_DATA}"
        chmod 700 "${USER_DATA}"
        "${USER_DATA}"
      fi

      chmod 600 "${USER_DATA}"
      echo 'do not delete' > "${LOCK}"
      logger -t "cloud" "user-data executed"
    fi
    else
      logger -t "cloud" "user-data is not a executable script"
    fi
fi
exit 0
