#!/bin/bash 
#
# Init file for SSH Public Keys Download Client
#
# chkconfig: 2345 98 02
# description: SSH Public Keys Download Client
### BEGIN INIT INFO
# Provides:          cloud-set-guest-sshkey
# Required-Start:    $sshd $network
# Required-Stop:     $sshd $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sets root ssh key
# Description:       Sets the ssh key for the root user based upon keys stored by the CloudStack RouterVM
### END INIT INFO


# Modify this line to specify the user (default is root)
user=root
sleep 10


# Add your DHCP lease folders here
DHCP_FOLDERS="/var/lib/dhclient/* /var/lib/dhcp3/* /var/lib/dhcp/* /var/lib/NetworkManager/*"
keys_received=0
file_count=0

for DHCP_FILE in $DHCP_FOLDERS
do
	if [ -f $DHCP_FILE ]
	then
		file_count=$((file_count+1))
		SSHKEY_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')

		if [ -n $SSHKEY_SERVER_IP ]
		then
			logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"

			publickey=$(wget -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys 2>/dev/null)

			if [ $? -eq 0 ]
			then
				logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
				keys_received=1
				break
			fi
		else
			logger -t "cloud" "Could not find ssh key server IP in $DHCP_FILE"
		fi
	fi
done

# did we find the keys anywhere?
if [ "$keys_received" == "0" ]
then
    logger -t "cloud" "Failed to get ssh keys from any server"
    exit 1
fi



# set ssh public key
homedir=$(grep ^$user /etc/passwd|awk -F ":" '{print $6}')
sshdir=$homedir/.ssh
authorized=$sshdir/authorized_keys


if [ ! -e $sshdir ]
then
    mkdir $sshdir
fi

if [ ! -e $authorized ]
then
    touch $authorized
fi

cat $authorized|grep -v "$publickey" > $authorized
echo "$publickey" >> $authorized


exit 0
